<?xml version="1.0" encoding="utf-8"?>
<!-- File: Directory.Packages.props
 All packages are listed in this file, and each project or Directory
 file references packages relevent to that project.
 -->
<Project>
  <PropertyGroup>
    <!-- Enable central package management
     https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management
     -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- Versions -->
  <ItemGroup Label="Common">
    <PackageVersion Include="Parlot" Version="1.5.6" />
  </ItemGroup>
  <ItemGroup Label="OrgMode" />
  <ItemGroup Label="Build">
    <PackageVersion Include="GitVersion.MsBuild" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="MSTest" Version="4.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>
</Project>