<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ParentDirectoryBuildPropsPath>
    $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))
  </ParentDirectoryBuildPropsPath>
  </PropertyGroup>
  <ImportGroup>
    <Import Project="$(ParentDirectoryBuildPropsPath)" />
  </ImportGroup>
  <PropertyGroup Label="Testing">
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
    <TestingPlatformCaptureOutput>true</TestingPlatformCaptureOutput>
  </PropertyGroup>
  <PropertyGroup Label="Code Quality">
    <ErrorLog>$(ArtifactDirectory)\CodeQuality\$(MSBuildProjectName).json</ErrorLog>
  </PropertyGroup>
</Project>
